# Nome da sua GitHub Action
name: Generate Snake Animation

permissions:
  contents: write

# Controla quando a Action será executada
on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"

  # Permite que você execute a Action manualmente na aba "Actions"
  workflow_dispatch:

# As tarefas que a Action vai realizar
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Prepara o repositório para que a Action possa salvar o arquivo gerado
      - uses: actions/checkout@v3

      # Passo 2: Gera a animação da cobra e salva na pasta "dist"
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # O seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}

          # Onde salvar os arquivos gerados (o .svg da cobra)
          outputs: dist/github-contribution-grid-snake.svg

      # Passo 3: Envia o arquivo gerado de volta para o seu repositório
      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
